# Final Grant Blog


As I have continued to flush out the details of my Grant Project: Travel with the Greats: Van Gogh, Monet, Picasso Mapping Project, I have not noticed any significant changes to my process. However, I did want to focus more heavily on the value or purpose behind my project and how I would relay this to my audience. In order to do so, I still needed to solidify my research into the three artists to have a firm understanding of my project’s contents and therefore its purpose.

I conducted further research in order to insure the accuracy of the information I had obtained regarding the three artists I chose to focus on. I came across several pieces that were enlightening and truly expressed what driven, talent geniuses these artists were during their time and currently. I was specifically drawn to an interview of sorts conducted by Anna Seaton Schmidt, a journalist from the late 1800s, who spoke with Monet in his home. Monet’s descriptions of his process were fascinating and brought such inspiration to myself, who am also an artist. He described his paintings as, “...my impression of nature. It is most difficult to explain. It is the brain that makes the picture, it is a distinct gift, a talent” (Monet, 1897)

![Monet Interview](https://sambuc214.github.it/sambuchholz/images/MonetInterview.png)
 
This type of personal information and insight is exactly what I wish to convey in my project. These little quotes or details from a famous artist’s life makes their genius both more attainable and intimidating to young artists who are looking for a baseline of inspiration to start their artistic journey. By humanizing famous artists, I aim to lessen the pressure put on people who are just starting out in their creative endeavors and make them feel more comfortable in their own style.

Writing this grant has increased my awareness of the vital importance of not only researching a topic, but fully understanding the purpose and value of a project. While I personally believe that my project is of value to me, writing this grant has pushed me to emphasize its value to others. I was able to pull from my own experience as an artist in finding what I believe most young or aspiring artists long for: a solid base of inspiration to start from.

The software needed for this kind of project is also something that I was unfamiliar with. I had no idea that this amount of time and effort would come into play when creating something that myself and the general public might see as simple in a website. I have continued gathering more information about the three artists to adequately supply my site. I have also looked into more software options for the creation of the site, however I have concluded that the ones that I had chosen are still the best choices. These include Omeka, Neatline, and Lynda.com.

Overall, the grant has allowed me to expand on my writing skills as well as my project development capabilities. It was fascinating to come up with a project that, although I was not actually creating, I still had to completely form in its entirety on paper. My appreciate for grant writers and DH project creators have increased dramatically and I hope to convey this through my grant and project idea.
